# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
#  host: localhost
  username: root
  password: root

development:
  <<: *default
  database: xls_dev

production:
  <<: *default
  database: xls_prod

test:
  <<: *default
  database: xls_test
